name: "Build and release it in GITHUB"
on:
  push:
    branches:
      - master
jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game to GITHUB
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: create game release
        uses: firebelley/godot-export@v3.0.0
        with:
          # Defining all the required inputs
          # I used the mono version of Godot in this example
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4/mono/Godot_v3.4-stable_mono_linux_headless_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4/mono/Godot_v3.4-stable_mono_export_templates.tpz
          # set this either to . or your game path, e.g. ./godot in case
          # your game is within a sub-directory
          relative_project_path: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
