name: "Publish to itch.io"
on:
  release:
    types: [published]
jobs:
  release_html:
    runs-on: ubuntu-latest
    name: fetch from GITHUB
    steps:
      - name: download zip file
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: space-shotr.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: HTML
          ITCH_GAME: space-shotr
          ITCH_USER: kerodekroma
          PACKAGE: space-shotr.zip
          VERSION: ${{ steps.download-html.outputs.version }}

  release_win:
    runs-on: ubuntu-latest
    name: fetch from GITHUB
    steps:
      - name: download zip file
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: space-shotr-win.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: space-shotr
          ITCH_USER: kerodekroma
          PACKAGE: space-shotr-win.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
